[package]
name = "ipc-rs"
version = "0.4.4"
authors = ["Sameer Ahmad <sameerahmad990@gmail.com>"]
edition = "2021"

[dependencies]
nix = { version = "0.28.0", features = ["signal", "time"] }
libc = "0.2.43"
crossbeam-utils = "0.8.19"
